### ISSUE TITLE
upgrade to 0.14.1

### ISSUE THREAD

**Issue by iandol** [x-cmd-build/zenith#2]
0.14.1 was released in May

**Comment by lunrenyi** [comment]
x-cmd-build zenith has been updated to version 0.14.1.
```sh
x pkg update
x env use zenith
```

**Comment by iandol** [comment]
thank you!

**Comment by iandol** [comment]
Hi, I used `x env use zenith` and selected option (1) which i thought upgrades the older version, but it is still installed: 

```
➪ x env ls -i

 Select...                                                                                                               
 eza/v0.19.4         fzf/v0.55.0         yazi/v0.3.0                                                                     
 7za/v0.0.1          gum/v0.14.1         yq/v4.44.2                                                                      
 bash-preexec/v0.5.0 gum/v0.14.5         zenith/v0.14.0                                                                  
 bat/v0.24.0         hyperfine/v1.18.0   zenith/v0.14.1 
```

I want to upgrade without ending up with multiple versions installed?

**Comment by qiakai** [comment]
you can use 
```sh
x env gc zenith=v0.14.0
```

**Comment by edwinjhlee** [comment]
You can try `x env gc` to remove the old instances.

Removing the old versions of software will be risky in x-cmd's situation, some script and shell session might running the software with `x env try` or `x <pkg>` or simply being dependency of other tool . If we suddenly remove it during upgrade, it will cause unknown behaivor.

That's the reason we introduce `gc` concept. If you unuse a package/version, the links of this version will be removed ( no longer activated ), and the files of this package/version will still exists.

**Comment by iandol** [comment]
How about a `x env cleanup` to deliberately remove old versions (Ruby's `gem` does this for example)?

**Comment by edwinjhlee** [comment]
You can run the two commands below and compare the output:

```
x env ls -u
x env ls -i
```

**Comment by iandol** [comment]
The problem with `x env ls` is it always uses a TUI which does not retain the text on the screen, and requires a [ctrl]+[d] to exit, overall the TUI serves no really useful purpose in this case, I think the default should be text, with maybe some option like `x env ls --tui -i` to show the TUI?

**Comment by edwinjhlee** [comment]
> How about a `x env cleanup` to deliberately remove old versions (Ruby's `gem` does this for example)?

The problem is, the old version is not that useless in x-cmd's situation.

Consider long-running tasks like `x <tool-a-with-old-version> | x jq` may break if the dependency (`tool-a-with-old-version`) is too easily removed.


It is quite a delima for x-cmd sometimes. From the perspective of developer, they can handle the complexity. So we need to provide updated versions of tools. However, from the perspective of command line users ( system op engineers ), we need to provide stabile version. I cannot ask the system op engineers to declare it is long-running beforehead to ensure these tools are not removable for some time.

That's the reason I sacrificed the disk space efficiency.

**Comment by edwinjhlee** [comment]
> The problem with `x env ls` is it always uses a TUI which does not retain the text on the screen, and requires a [ctrl]+[d] to exit, overall the TUI serves no really useful purpose in this case, I think the default should be text, with maybe some option like `x env ls --tui -i` to show the TUI?

Now You can try `x env ls | cat`.

Our of concerns of stability, we don't update the design of pkg for nearly a year. I will relocate the positioning of x-cmd/{pkg,env} reagarding the existence of pixi and redesign pkg/env in the comming months -- we won't break the compatibility.

**Comment by edwinjhlee** [comment]
> How about a `x env cleanup` to deliberately remove old versions (Ruby's `gem` does this for example)?

`x env gc` is `x env cleanup`. 

We don't remove old versions. We removed versions are not being used, and not being depeneded.

So when you `x env use zenith=latest`. The old zenith will be unuse but won't removed. You will need to apply gc to remove it.

Normally, the classic `x env upgrade zenith` will be like:

```
x env gc zenith
x env use zenith=lateset
```

What if an old zenith is running using `x env try` or not running but considered ready in the long-running script ? 
That's the scenairo I deeply concerns and introduce all of these mess.

I don't like this mess. It haunt me almost a year ~ But I have to ensure it is right first. Then I will improve and simplify it.

**Comment by edwinjhlee** [comment]
I think I might introduce the new scheme using directory links and reference count to handle the situation `x <tool-a-with-old-version> | x jq` ~

In short, it can be simplified, undoubtly. But requiring a much more complicated ref scheme and related gc. Once it is done, I will hide the output `x env ls -i` and make the gc more automcatically and friendly.

**Comment by edwinjhlee** [comment]
> The problem with `x env ls` is it always uses a TUI which does not retain the text on the screen, and requires a [ctrl]+[d] to exit, overall the TUI serves no really useful purpose in this case, I think the default should be text, with maybe some option like `x env ls --tui -i` to show the TUI?


ctlr-d to exit without retaining output.
ctlr-c to exit interruptedly so output is retained.

I will make it as a consistent design rule in all of our tui application.

**Comment by iandol** [comment]
> However, from the perspective of command line users ( system op engineers ), we need to provide stability.

`x env cleanup` is an optional command, no one will force them to run this. At least in my usecase, I prefer to keep my software up to date, so I run a script to do this knowing new versions may break, i.e. it would be **my** fault if it does, not your fault. You can just warn in the doc that `cleanup` may break long-running commands. I appreciate you want to "protect" your users.

Regarding [ctrl]+[d][c] I find this not so ergonomic, on my laptop it force me to move hand back and so i really prefer [q] or [esc]

**Comment by edwinjhlee** [comment]
x env cleanup is an optional command, no one will force them to run this. At least in my usecase, I prefer to keep my software up to date, so I run a script to do this knowing new versions may break, i.e. it would be my fault if it does, not your fault. You can just warn in the doc that cleanup may break long-running commands. I appreciate you want to "protect" your users.

--- 

Yes. I do realize it. And we call it `x env gc`. 

Currently It collects undepended packages automatically. But it doesn't collect the packages unused -- Like I said, it might be activated in some shell session implictly -- and users don't even konw it because x-cmd's modules use them implicitly.

I have to figure out the risks first. For system op engineers, it must be stable enough. I think people can accept the consequence that the x-cmd break down -- they can remove ~/.x-cmd.root and resinstall. 

However, what if some long running scripts are performaning some data backup or some jobs, and the script doesn't anticipate the tools might suddenly disappear. That sometimes will be disastrous.

The best practise is they create a project workspace just for this script.

---

Consider all of these situations and people I know, one year ago I sacrificed the disk-space efficiency.

---

For the scenarios you mentioned, I will consider providing a automcatically clean up scheme for unused packages. Like `x env gc --unuse` with warnings.

**Comment by edwinjhlee** [comment]
Regarding [ctrl]+[d][c] I find this not so ergonomic, on my laptop it force me to move hand back and so i really prefer [q] or [esc]

---

We won't provide q to exit because user may type q to filter some output.
But we can introduce ESC as ctrl-d.

---

About ctrl-c, I think it is widely used in the terminal scenairo. It sends interrupt signal to the programs. Most of the programs ( like cat, wc ) will return 130 as exit code so it is very easy to detect and log.

**Comment by edwinjhlee** [comment]
> The problem with `x env ls` is it always uses a TUI which does not retain the text on the screen, and requires a [ctrl]+[d] to exit, overall the TUI serves no really useful purpose in this case, I think the default should be text, with maybe some option like `x env ls --tui -i` to show the TUI?

I make it a design rule this year ( 2024 ) but haven't been appled to pkg/env ( because it is written in Dec, 2023 ) yet

```bash
ls -> For colorize table
nv -> For app
fz -> For fzf
```

We will refine pkg/env module in the next version [ v0.4.15 ].

**Comment by iandol** [comment]
> But we can introduce ESC as ctrl-d.

That would be awesome!
